-- Hyprland Configuration

-- Warning: Do not manually edit configuration files
-- Configuration files are maintained by HGS settings
-- Add manual configurations to ~/.config/hypr/hgs/custom.lua

hl.config({ autogenerated = false })

-- HGS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- HGS_STARTUP_END

hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^hgs:.*" }, no_anim = true })

hl.config({
    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo   = false,
    },
})

require("hgs.general")
require("hgs.animations")
require("hgs.colors")
require("hgs.cursor")
require("hgs.environment")
require("hgs.input")
require("hgs.keybinds")
require("hgs.layout")
require("hgs.misc")
require("hgs.monitors")
require("hgs.permissions")
require("hgs.rules")
require("hgs.user-keybinds")
require("hgs.custom")
