[templates.hgskitty]
input_path = 'SHELL_DIR/matugen/templates/kitty.conf'
output_path = 'CONFIG_DIR/kitty/hgs-theme.conf'

[templates.hgskittytabs]
input_path = 'SHELL_DIR/matugen/templates/kitty-tabs.conf'
output_path = 'CONFIG_DIR/kitty/hgs-tabs.conf'
