add_subdirectory(component)
add_subdirectory(hyprland)
add_subdirectory(compositord)
add_subdirectory(component-inspector)
add_subdirectory(coordinator)
add_subdirectory(configd)
add_subdirectory(componentd)
add_subdirectory(qml/HyprShelld/Client)
add_subdirectory(qml/HyprShelld/UI)
add_subdirectory(settings)
add_subdirectory(surfaced)
